### ISSUE TITLE
浏览器调用

### ISSUE THREAD

**Issue by wdh-1025** [mzule/ActivityRouter#11]
你好，在手机内置浏览器打开h5页面可以直接打开activity吗？同理，微信里面的内置浏览器可以打开app页面吗？谢谢

**Comment by mzule** [comment]
@wdh-1025 这个要看浏览器的实现，一般内置的浏览器都是可以调用打开 Activity 的，微信里面不可以，猜测是微信维护了一个 scheme 的白名单，大多数 app 的 scheme 都不在白名单里面、
