### ISSUE TITLE
mappings为空，打不开对应的activity

### ISSUE THREAD

**Issue by mavisli** [mzule/ActivityRouter#12]
尝试理解源码，并没有直接引用，本地按照你的project进行配置
这是生成的RouterMapping类
// ----------------------------------------------------------

public final class RouterMapping {
  public static final void map() {
    java.util.Map<String,String> transfer = null;
    com.test.routerkit.router.ExtraTypes extraTypes;
    transfer = null;
    extraTypes = new com.test.routerkit.router.ExtraTypes();
    extraTypes.setTransfer(transfer);
    com.test.routerkit.router.Routers.map("main/test", MainActivity.class, extraTypes);
    com.test.routerkit.router.Routers.sort();
  }
}
// ----------------------------------------------------------
但是Routers.map()方法并没有调用, mappings size始终为0，无法打开对应的activity。
请问com.test.routerkit.router.Routers.map()失效的原因是什么

**Comment by mavisli** [comment]
done.  RouterMapping作为java library引用，非android library.
还是非常感谢。

**Comment by mzule** [comment]
👍
