### ISSUE TITLE
每次页面跳转的问题

### ISSUE THREAD

**Issue by RiversAndMountains** [mzule/ActivityRouter#13]
public class App extends Application implements RouterCallbackProvider {
    @Override
    public RouterCallback provideRouterCallback() {
        return new SimpleRouterCallback() {
            @Override
            public void beforeOpen(Context context, Uri uri) {
                context.startActivity(new Intent(context, LaunchActivity.class));
            }

            @Override
            public void afterOpen(Context context, Uri uri) {
            }

            @Override
            public void notFound(Context context, Uri uri) {
                context.startActivity(new Intent(context, NotFoundActivity.class));
            }

            @Override
            public void error(Context context, Uri uri, Throwable e) {
                context.startActivity(ErrorStackActivity.makeIntent(context, uri, e));
            }
        };
    }
}

我发现，每次调用跳转的时候，都会先执行到LaunchActivity里面；
而我希望当我回退的时候不经过这个LaunchActivity；
当我尝试注释掉 beforeOpen 里面的  启动 LaunchActivity 的时候，却发现无法执行；
请问这有好的解决办法么？
我希望，每次执行跳转的时候不去执行到 LaunchActivity，或者回退的时候不经过该页面；

**Comment by mzule** [comment]
>当我尝试注释掉 beforeOpen 里面的 启动 LaunchActivity 的时候，却发现无法执行；

这是什么意思？

**Comment by RiversAndMountains** [comment]
已经解决了，意思是，我试图在 beforeOpen 方法里不做任何事，注释掉了 context.startActivity(new Intent(context, LaunchActivity.class)); 
解决办法是 在 Router.open 时 不加上该 callback 回调；
