### ISSUE TITLE
url参数的问题

### ISSUE THREAD

**Issue by wutongke** [mzule/ActivityRouter#17]
当url中存在“／”符号时，会有解析错误的问题，觉得可以做一个过滤，提供一个encode的方法，然后回传参数的时候decode

**Comment by mzule** [comment]
参数中的 / 应该在生成 url 前自行 urlencode. 如

```
router://main?name=wu/tong/ke
↓
 "router://main?name="+urlencode("wu/tong/ke")
↓
router://main?name=wu%2Ftong%2Fke
```

这样在目标 Activity 通过 getIntent().getString("name") 得到的值就已经是 wu/tong/ke 了。

**Comment by wutongke** [comment]
谢谢

**Comment by wutongke** [comment]
发现参数编码后在生成path时
 String urlPath = uri.getPath()自动进行了解码，所以还是会得到错误的path，导致解析失败。

**Comment by mzule** [comment]
![image](https://cloud.githubusercontent.com/assets/2096572/19955156/8e6ef0ba-a1b9-11e6-95e0-abd7e21463ba.png)
