### ISSUE TITLE
配置多个@Router({"main", "root"})，如何确定是通过"main"打开的，还是通过"root"打开的

### ISSUE THREAD

**Issue by forgekxf** [mzule/ActivityRouter#18]

**Comment by forgekxf** [comment]
还有一种情况：app://goto/url/http%3A%2F%2Fm.huajuanmall.com%2Fsubject%2Fshuang112016     这样如何获取到后面的url呢?      @Router("goto/url/:url")这样定义好像不可以

**Comment by mzule** [comment]
第一个问题在 REAME 里面有说明。

### 支持获取原始 url 信息

``` java
getIntent().getStringExtra(Routers.KEY_RAW_URL);
```

 可以通过原始 url 判断是 main 还是 root

第二个问题应该是可以的，这个在 demo 里面有类似的参考。通过 

``` java
getIntent().getStringExtra("url");
```

来获得 url.
