### ISSUE TITLE
消息推送的时候使用路由无效

### ISSUE THREAD

**Issue by bobingxin** [mzule/ActivityRouter#19]
在收到推送消息后打开应用，但是通过Routers无法打开。

**Comment by mzule** [comment]
可以描述的更具体一些吗？

**Comment by bobingxin** [comment]
消息推送过来后，我们在broadcast receiver中收到通知，在这里面要做页面的跳转。
这样写无法打开
`Routers.open(context, "mk:main");`
这样写就可以了
`Intent intent = new Intent(context, MainActivity.class);
  intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP );
  context.startActivity(intent);`

**Comment by mzule** [comment]
``` java
Routers.open(context, "mk:main");
```
应该是
``` java
Routers.open(context, "mk://main");
```
吧

**Comment by bobingxin** [comment]
应该是没有设置Flag的原因吧，在broadcastreceiver中打开activity需要添加Intent.FLAG_ACTIVITY_NEW_TASK这个flag。

**Comment by bobingxin** [comment]
我这边的问题，那个地方写错了。想要使用singletask在这块，Intent.FLAG_ACTIVITY_CLEAR_TOP这个flag怎么添加呢？

**Comment by mzule** [comment]
`FLAG_ACTIVITY_NEW_TASK` ActivityRouter 会根据 Context 类型自动添加，`FLAG_ACTIVITY_CLEAR_TOP` 暂时还添加不了。。下一步我添加一个 Routers.resolve(url) 来获取 Intent 的方法吧，这样可以方便添加各种 Flag。。。你觉得如何？

**Comment by bobingxin** [comment]
好的，这样能解决我这种特殊的需求了。

**Comment by mzule** [comment]
好的，我周末处理一下哈。

**Comment by mzule** [comment]
@bobingxin 搞定了

``` groovy
compile 'com.github.mzule.activityrouter:activityrouter:1.2.1'
```

``` java
Intent intent = Routers.resolve(context, "mzule://main/0xff878798")
```

**Comment by bobingxin** [comment]
ok，谢谢了
