### ISSUE TITLE
怎么获取来自哪个请求？

### ISSUE THREAD

**Issue by van416** [mzule/ActivityRouter#2]
有一个问题，你定义了多个{"http://www.xxx.com/main", "main"}  目标activity怎么知道来自哪个类型的请求呢？

**Comment by mzule** [comment]
@van416 目前还没有这个功能，有这个需求吗？会有不一样的处理逻辑吗？

**Comment by van416** [comment]
是的，会有不一样的。一个activity可以会有几个fragment, 不通过参数，通过url来确定那个页面

**Comment by mzule** [comment]
@van416 新版本支持了，通过 `getIntent().getStringExtra(Routers.KEY_RAW_URL);`
