### ISSUE TITLE
如果打开失败了如何调适呢，有没有错误信息

### ISSUE THREAD

**Issue by imishx** [mzule/ActivityRouter#21]

**Comment by mzule** [comment]
日志应该都有的，你是应用类调用还是应用外调用？

**Comment by imishx** [comment]
应用内调适，open返回了false，但没有任何日志

**Comment by mzule** [comment]
返回 false 代表没有 match 到合适的 Activity，可以去检查一下 url 与 @Router 的配置。。

**Comment by imishx** [comment]
好吧，如果我想跳转应用外的Activity 如何配置呢

**Comment by mzule** [comment]
这已经是这个库之外的范畴了，还是去谷歌一下吧。
