### ISSUE TITLE
实际参数列表和形式参数列表长度不同

### ISSUE THREAD

**Issue by guiying712** [mzule/ActivityRouter#22]
Error:(13, 51) 错误: 无法将类 Routers中的方法 map应用到给定类型;
需要: String,Class<? extends Activity>,MethodInvoker,ExtraTypes
找到: String,Class<GirlsActivity>,ExtraTypes
原因: 实际参数列表和形式参数列表长度不同

**Comment by mzule** [comment]
请检查一些你的两个依赖的版本是不是都是最新的。

```
dependencies {
    compile 'com.github.mzule.activityrouter:activityrouter:1.2.1'
    apt 'com.github.mzule.activityrouter:compiler:1.1.7'
}
```
