### ISSUE TITLE
RouterInit这个类不存在

### ISSUE THREAD

**Issue by pphdsny** [mzule/ActivityRouter#23]
导入的是下面的库
    compile 'com.github.mzule.activityrouter:activityrouter:1.2.1'
    apt 'com.github.mzule.activityrouter:compiler:1.1.7'
RouterInit这个类不存在，看了源码中还引入了一个“stub”的字库，里面有RouterInit这个类，但是我通过gradle引入就找不到这个类！

**Comment by mzule** [comment]
这个类是自动生成的， stub 的库是编译时依赖，发布的 SDK 不会包含这个类。

**Comment by pphdsny** [comment]
我没有自动生成，而且自定义Router注解，在open的时候也找不到

**Comment by mzule** [comment]
`自定义Router注解`这是啥？

**Comment by pphdsny** [comment]
就是@Router这个定义Activity的路由

**Comment by mzule** [comment]
你用的什么 IDE，是不是没开 AnnotationProcessor?

**Comment by pphdsny** [comment]
AnnotationProcessor还需要我自己打开的么？我用的AS

**Comment by mzule** [comment]
我的 QQ: 786553789, 我们 QQ 沟通吧，方便解决问题。

**Comment by mzule** [comment]
QQ 上沟通，发现原因是 apt 配置在了 library module 里面而不是主工程里面，导致的主工程的 apt 没有执行。
