### ISSUE TITLE
拦截器

### ISSUE THREAD

**Issue by luxiao0314** [mzule/ActivityRouter#29]
不支持拦截器吗,跳转之前拦截做登录绑卡的操作等这样,我看alibaba/ARouter有加

**Comment by mzule** [comment]
在计划中，不过年底了工作太忙了，你有兴趣提个 pull request 吗？

**Comment by luxiao0314** [comment]
试一下

**Comment by mzule** [comment]
搞好啦，借用 beforeOpen 返回一个 boolean 就可以了，欢迎验证 @luxiao0314
