### ISSUE TITLE
为什么我这么写 浏览器打不开呢

### ISSUE THREAD

**Issue by ruhaly** [mzule/ActivityRouter#3]
@RequiresPresenter(PayPresenter.class)
@Router("main")
public class RechargePayActivity extends BaseActivity<PayPresenter> implements View.OnClickListener, IPayView {}

 <activity android:name="com.luichi.ygj.view.activity.RechargePayActivity">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="mzule" />
            </intent-filter>
        </activity>
为什么我这么写 浏览器打不开呢

**Comment by mzule** [comment]
你是通过什么方式尝试打开的？
