### ISSUE TITLE
多工程怎么使用？

### ISSUE THREAD

**Issue by sua022** [mzule/ActivityRouter#31]
项目里很多模块是通过lib工程来实现的，这种情况怎么使用？在每个lib工程都配置会生成相同的类，如果只在主工程里配置那lib工程的Annotation又不生成代码。

**Comment by mzule** [comment]
支持的，readme 暂时没有更新，参考下面说明以及 demo：

1. 每个包含 activity 的 module 都要添加 apt 依赖
2. 每个 module(包含主项目) 都要添加一个 @Module(name) 的注解在任意类上面，name 是项目的名称
3. 主项目要添加一个 @Modules({name0, name1, name2}) 的注解，指定所有的 module 名称集合

**Comment by yanxinmiao** [comment]
@mzule 按照你说的123设置好后，启动activity 怎么写啊？什么格式
