### ISSUE TITLE
组件化多module情况下跳转会失败或者跳到另一个页面

### ISSUE THREAD

**Issue by a1048823898** [mzule/ActivityRouter#34]

**Comment by mzule** [comment]
请问是什么页面？两个页面设定的 url 规则有什么联系吗？

**Comment by iluhcm** [comment]
我在看源码也发现了，demo中的app和sdk两个module，但最终生成的只有RouterMapping_app.java，没有RouterMapping_sdk.java。

**Comment by mzule** [comment]
发现了是指什么？最终这两个文件都会生成的，除此之外还会有 RouterInit.java

**Comment by suethan** [comment]
组件化多module如何配置呢？

**Comment by mzule** [comment]
@suethan 参考这个 https://github.com/mzule/ActivityRouter/issues/31

**Comment by 985557461** [comment]
到底解决了没有啊？我们项目要进行拆分，这个很重要
