### ISSUE TITLE
为啥项目中依赖了这个库  ButterKnife就不能用了?

### ISSUE THREAD

**Issue by Ryokooo** [mzule/ActivityRouter#36]

**Comment by stormlei** [comment]
+1 @mzule

**Comment by mzule** [comment]
你的 butterknife 使用的官方的 AnnotationProcessor 吗？可能与 apt 之间有冲突，需要做一下改动，使用官方的 AnnotationProcessor 来处理 ActivityRouter.

根目录 build.gradle 相关的配置不再需要了，直接删掉。

项目的 build.gradle 相关配置简化成如下。

``` groovy
dependencies {
    compile 'com.github.mzule.activityrouter:activityrouter:1.2.2'
    annotationProcessor 'com.github.mzule.activityrouter:compiler:1.1.7'
}
```

如果你确定成功了，我会在 readme 里面补充一下说明。或者欢迎给我提 PR.

**Comment by Ryokooo** [comment]
嗯..这样就可以用了..谢谢!

**Comment by simplehych** [comment]
确实存在这个问题，和ButterKnife冲突，请有时间更新一下readmine
另：这个配置是应该在项目的每一个module都进行配置的吧，包括主module
```
dependencies {
    compile 'com.github.mzule.activityrouter:activityrouter:1.2.2'
    annotationProcessor 'com.github.mzule.activityrouter:compiler:1.1.7'
}
```

**Comment by mzule** [comment]
谢谢提醒，我待会就改 readme, 另外不是和 ButterKnife 冲突，是官方的 annotationProcessor 和 apt 不能共用。

是否需要在所有 module 配置这个要看需求。
