### ISSUE TITLE
ActivityRouter 支持Google官方提供的分包方案Multidex吗？

### ISSUE THREAD

**Issue by 985557461** [mzule/ActivityRouter#42]

**Comment by mzule** [comment]
和 Multidex 一起用有遇到什么问题吗？

**Comment by 985557461** [comment]
目前还没有，只不过想找你确定一下

**Comment by 985557461** [comment]
测试发现：java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/mzule/activityrouter/router/RouterInit;

**Comment by 985557461** [comment]
测试发现：java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/mzule/activityrouter/router/RouterInit;
