### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/mzule/activityrouter/router/RouterInit;

### ISSUE THREAD

**Issue by 985557461** [mzule/ActivityRouter#46]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/mzule/activityrouter/router/RouterInit;

**Comment by 985557461** [comment]
已经解决

**Comment by ChrisZou** [comment]
能说一下是怎么解决的吗？我也遇到这个问题了。

**Comment by ChrisZou** [comment]
已解决，我的@Route用在kotlin定义的class上面了，要用kapt
