### ISSUE TITLE
stringParam，字符串参数如果使用的时候为空，无法跳转

### ISSUE THREAD

**Issue by JerryloveEmily** [mzule/ActivityRouter#48]
String accountParam = mEtdAccount.getText().toString().trim();
// accountParam为空字符串的时候，无法跳转，我是做了一个判断加了一个为空串的时候的标识。
if (TextUtils.equals("", accountParam)){
      // 帐号参数为空字符串的时候，路由的url路径无法跳转，所以设置一个空的标识来表示
       accountParam = "empty";
}
Routers.openForResult(LoginActivity.this,
                        AppConst.MODIFY_PWD_ROUTER_URL + accountParam,
                        AppConst.MODIFY_PWD_REQUEST_CODE);

**Comment by mzule** [comment]
这和 url 规范有关，这种情况建议使用 QueryParams 参数传递 account
