### ISSUE TITLE
怎么调用静态方法啊 

### ISSUE THREAD

**Issue by qq634421026** [mzule/ActivityRouter#49]
readme 这块写的不是很懂 求请教

**Comment by simplehych** [comment]
和调用 Activity 方式一样 `Routers.openForResult()` 或者 `Routers.open()`
@mzule 调用静态方法 `logout()` 和 `uploadLog()` 吐司没有响应
需要将布局文件中的 `mzule ` 修改为 `router` ？
```
        <TextView
            style="@style/Menu"
            android:text="**mzule** ://upload" />
        <TextView
            style="@style/Menu"
            android:text="**mzule** ://logout" />
```
=>
```
        <TextView
            style="@style/Menu"
            android:text="**router**://upload" />

        <TextView
            style="@style/Menu"
            android:text="**router**://logout" />
```

**Comment by qq634421026** [comment]
@simplehych 对的 需要把mzule改成router 因为在清单文件里RouterActivity的scheme是router

**Comment by mzule** [comment]
谢谢，之前 scheme 写错了，现已被 @simplehych  修复~

**Comment by simplehych** [comment]
请问调用静态方法怎么使用，能传值吗？静态方法写成有返回值的该如何接收吗？ 代码里好像没有做这方面的处理，只是invoke了该方法，请问 **传值进入** 或 **返回接收** 怎么实现，谢谢 @mzule

**Comment by mzule** [comment]
@simplehych 传值通过 scheme 拼接实现，如 router://logout?name=value，然后再在 bundle 里面取值; 返回值不支持。

**Comment by simplehych** [comment]
好的，谢谢

**Comment by simplehych** [comment]
@mzule  好的，谢谢
