### ISSUE TITLE
module启动activity失败

### ISSUE THREAD

**Issue by liy452083759** [mzule/ActivityRouter#62]
在lib中启动app的activity失败,
想知道是什么原因,是包名的问题,还是Application的问题,
启动lib中的activity就是正常的

**Comment by totothink** [comment]
你的代码是怎么写的？

**Comment by liy452083759** [comment]
在一个common库中导入的 
 compile 'com.github.mzule.activityrouter:activityrouter:1.2.2'
    apt 'com.github.mzule.activityrouter:compiler:1.1.7'
可以在app中启动module的activity ,但是从module中启动不了app的activity
按照#53做了之后还是报错,找不到我配置的activity;
请问这个是你的邮箱吗?mzule.4j@gmail.com;
有点不懂这个是什么邮箱

**Comment by totothink** [comment]
参考ActivityRouter源代码，在每个module建立Module类并用@Module注解，在App类中用@Modules注解。

**Comment by liy452083759** [comment]
找到问题了,原来在每个需要使用的库和app中都需要添加那个编译插件的库
