### ISSUE TITLE
assets下存放一个html，html加的a标签跳转APP中的activity失败

### ISSUE THREAD

**Issue by 1242128273wangpeng** [mzule/ActivityRouter#65]
![0e097ecf4fdd029c26591da11244f0a0](https://user-images.githubusercontent.com/10842360/27268634-6d2640b0-54e3-11e7-9754-dc1fa948e54d.jpg)

**Comment by mzule** [comment]
需要通过 WebViewClient 的 shouldOverrideUrlLoading 处理

**Comment by palorotolo** [comment]
具体是怎么处理？
