### ISSUE TITLE
Routers中的RouterInit.init();一直报红色，点击无法跳转

### ISSUE THREAD

**Issue by liushengqiang** [mzule/ActivityRouter#67]
错误日志：
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/mzule/activityrouter/router/RouterInit;
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at com.github.mzule.activityrouter.router.Routers.initIfNeed(Routers.java:26)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at com.github.mzule.activityrouter.router.Routers.doOpen(Routers.java:123)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at com.github.mzule.activityrouter.router.Routers.open(Routers.java:86)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at com.github.mzule.activityrouter.router.Routers.open(Routers.java:58)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at com.github.mzule.activityrouter.router.Routers.open(Routers.java:54)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at com.lzmh.lzmhdemo.KeDaXunFei.KeDaXunFeiTestActivity.onClick(KeDaXunFeiTestActivity.java:53)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at android.view.View.performClick(View.java:5721)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at android.widget.TextView.performClick(TextView.java:10949)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at android.view.View$PerformClick.run(View.java:22624)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at android.os.Looper.loop(Looper.java:148)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7407)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1321)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1211)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.mzule.activityrouter.router.RouterInit" on path: DexPathList[[zip file "/data/app/com.lzmh.lzmhdemo-1/base.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.lzmh.lzmhdemo-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.lzmh.lzmhdemo-1/lib/arm, /data/app/com.lzmh.lzmhdemo-1/base.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.lzmh.lzmhdemo-1/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err: 	... 16 more
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.github.mzule.activityrouter.router.RouterInit
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at java.lang.Class.classForName(Native Method)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err: 		... 17 more
07-19 11:36:34.082 13008-13008/com.lzmh.lzmhdemo W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by liuzhenhuanet** [comment]
这是注解处理器没有正常工作，你检查一下你的gradle文件里是不是还引入了其他跟注解处理器有关的东西，例如kotlin，如果是用了kotlin，请参考https://www.kotlincn.net/docs/reference/kapt.html配置你的gradle文件

**Comment by liushengqiang** [comment]
我原来是没有看到下面这些，后来，参考了demo加上去了，但是在编译时RouterInit中其他模块的map提示找不到符号，这又怎么解决呢：
每个包含 activity 的 module 都要添加 apt 依赖
每个 module(包含主项目) 都要添加一个 @Module(name) 的注解在任意类上面，name 是项目的名称
主项目要添加一个 @Modules({name0, name1, name2}) 的注解，指定所有的 module 名称集合

**Comment by liushengqiang** [comment]
我已经添加了相关注解还是不行：
@Modules({"app","VoicePassword"})
public class LzmhApplication extends Application {
}

@Module("app")
public class AppModule {
}

@Module("VoicePassword")
public class voicepassword {
}

**Comment by liushengqiang** [comment]
发现你的demo中RouterInit的其他模块的map也是报红色的，但是你的demo可以编译过去，我的却不行，提示找不到符号，奇怪了

**Comment by chewu1590** [comment]
你的问题解决了吗，我也碰到了一样的问题@liushengqiang

**Comment by liushengqiang** [comment]
我当时是app目录下的gradle没有配置好，配置好后如下：
if (!IsBuildMudle.toBoolean()){
    compile project(':voicepassword')
}
